title: Kieu My Giang 
logo: "/images/profilepicture.png?raw=true" 
description: >
  I am a graduate student in MS. Business Analytics at Zicklin 
  School of Business (Baruch College, NYC). I am passionate about using different 
  tools and sifting through big data to gain actionable insights for improving business,
  changing people's lives and making this world a better place.
  <br><br>
  <a href="https://www.linkedin.com/in/my-giang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

